apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-model-cache-gpt-oss-120b
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: standard-gce-pd
