apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-model-cache-gemma-27b
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: standard-gce-pd
