apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-vllm-gemma-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-gemma-server
  template:
    metadata:
      labels:
        app: blue-gemma-server
        # 1 billion parameter model (smallest)
        ai.gke.io/model: gemma-3-1b-it
        ai.gke.io/inference-server: vllm
        examples.ai.gke.io/source: user-guide
    spec:
      containers:
      - name: inference-server
        image: us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/pytorch-vllm-serve:20250312_0916_RC01
        resources:
          requests:
            cpu: "2"
            memory: "10Gi"
            ephemeral-storage: "10Gi"
            nvidia.com/gpu: "1"
          limits:
            cpu: "2"
            memory: "10Gi"
            ephemeral-storage: "10Gi"
            nvidia.com/gpu: "1"
        command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]
        args:
        - --model=$(MODEL_ID)
        - --tensor-parallel-size=1
        - --host=0.0.0.0
        - --port=8085
        env:
        # 1 billion parameter model (smallest)
        - name: MODEL_ID
          value: google/gemma-3-1b-it
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_token
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        livenessProbe:
          httpGet:
            path: /v1/models # Use the confirmed health endpoint
            port: 8085
          initialDelaySeconds: 300 # Give time for model to load (5 minutes)
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v1/models # Use the confirmed health endpoint
            port: 8085
          initialDelaySeconds: 300 # Give time for model to load (5 minutes)
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: dshm
        emptyDir:
            medium: Memory
      nodeSelector:
        # Nvidia L4 GPU
        cloud.google.com/gke-accelerator: nvidia-l4
        cloud.google.com/gke-gpu-driver-version: latest
