apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: blue-vllm-gemma-healthcheck-policy
  namespace: default # Or the namespace where your vLLM Service is
spec:
  targetRef:
    group: "" # Core API group for Service
    kind: Service
    name: blue-llm-service
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /v1/models # The health endpoint you confirmed earlier
        port: 8085 # The targetPort your vLLM app listens on

