apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-gemma-3-27b-a100
  labels:
    # --- Labels for selection ---
    app: vllm-gemma-3-27b-a100
    # --- Labels for GKE Observability ---
    ai.gke.io/model: gemma-3-27b-it # Correct model
    ai.gke.io/inference-server: vllm
    examples.ai.gke.io/source: user-guide
spec:
  replicas: 1
  selector:
    matchLabels:
      # This MUST match the pod template's app label
      app: vllm-gemma-3-27b-a100
  template:
    metadata:
      labels:
        # --- Label for selection ---
        app: vllm-gemma-3-27b-a100
        # --- Labels for GKE Observability ---
        ai.gke.io/model: gemma-3-27b-it # Correct model
        ai.gke.io/inference-server: vllm
        examples.ai.gke.io/source: user-guide
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-a100-80gb
      containers:
      - name: vllm-server
        image: vllm/vllm-openai:latest
        resources:
          limits:
            nvidia.com/gpu: 4
        command: ["/bin/sh", "-c"]
        args:
          - >-
            python -m vllm.entrypoints.openai.api_server
            --model google/gemma-3-27b-it
            --served-model-name gemma-3-27b-it
            --tensor-parallel-size 4
            --gpu-memory-utilization 0.95
            --max-model-len 16384
            --trust-remote-code
            --host 0.0.0.0
            --port 8000
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_api_token
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
