apiVersion: monitoring.googleapis.com/v1
kind: ClusterPodMonitoring
metadata:
  name: nvidia-dcgm-exporter-for-hpa
spec:
  selector:
    matchLabels:
      # This selector targets the DCGM exporter pods.
      app.kubernetes.io/name: gke-managed-dcgm-exporter
  endpoints:
  - port: metrics
    interval: 15s
    metricRelabeling:
    - sourceLabels: [__name__]
      regex: 'DCGM_FI_DEV_GPU_UTIL'
      action: replace
      replacement: 'dcgm_fi_dev_gpu_util'
      targetLabel: '__name__'
