# Scrapes *and* translates the nvidia gpu metric
# into the managed prometheus repository. Must be
# cluster pod monitoring because the targeted
# dcgm export pods live in the gke-managed-system
# namespace, and we can not set up a pod monitoring
# resource (or any resource) in that restricted
# namespace. This resource is necessary to lower-case
# gpu metric, since upper-case metrics do not work.
apiVersion: monitoring.googleapis.com/v1
kind: ClusterPodMonitoring
metadata:
  name: nvidia-dcgm-exporter-hpa-source
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gke-managed-dcgm-exporter
  endpoints:
  - port: metrics
    interval: 15s
    metricRelabeling:
    - sourceLabels: [__name__]
      regex: 'DCGM_FI_DEV_GPU_UTIL'
      action: keep
