# ---
# Purpose: This Rules resource defines a Prometheus recording rule. Recording
#          rules allow you to precompute frequently needed or computationally
#          expensive expressions and save their result as a new set of time series.
#
# Why is this needed?
# The original NVIDIA metric is named `DCGM_FI_DEV_GPU_UTIL` (uppercase).
# Some systems, including potentially the HPA metric path, can be case-sensitive
# or have trouble with uppercase metric names. This rule creates a new, identical
# metric named `dcgm_fi_dev_gpu_util` (lowercase) as a workaround to ensure
# compatibility.
# ---
apiVersion: monitoring.googleapis.com/v1
kind: Rules
metadata:
  name: nvidia-dcgm-hpa-rules
  namespace: default
spec:
  groups:
  - name: dcgm.rules
    interval: 15s # The interval at which the rule is evaluated. Should typically match the scrape interval.
    rules:
    # This is the definition of the new time series to create.
    - record: dcgm_fi_dev_gpu_util # The name of the NEW, lowercase metric.
      # The expression that generates the value for the new metric.
      # In this case, it simply copies the value from the original uppercase metric.
      expr: DCGM_FI_DEV_GPU_UTIL
