apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gemma-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vllm-gemma-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metric:
        name: prometheus.googleapis.com|vllm:num_requests_running|gauge
      target:
        type: AverageValue
        # If average scale threshold for metric
        averageValue:  4
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30 # <-- Waits 30 seconds before scaling down
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
